name: Manual_Deploy
on:
  workflow_dispatch:

env:
    DOTNETVERSION: 8.0.x
    DOCKER_FILE_PATH: /var/finaldockertestdir/
    PUBLISH_FILE_PATH: /var/finaltestdir/
    DOCKER_COMPOSE_FILENAME: docker-compose.Development.yml

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:  '${{env.DOTNETVERSION}}'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release

      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./publish

      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: distfiles

      - name: Copy docker-compose.yml to distfiles
        run: |
          cp docker-compose.yml distfiles/;
          cp Dockerfile distfiles/

      - name: copy file to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DPLY_USER }}
          key: ${{ secrets.KEY }}
          port: 22
          overwrite: true
          source: distfiles/*
          target: /var/stafftestdir/

      - name: Update Server-Side Scripts
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DPLY_USER }}
          key: ${{ secrets.KEY }}
          script: |
            cp /var/stafftestdir/distfiles/Dockerfile ${{ env.DOCKER_FILE_PATH }}; 
            cp /var/stafftestdir/distfiles/docker-compose.yml ${{ env.DOCKER_FILE_PATH }}; 
            rm -f /var/stafftestdir/distfiles/Dockerfile;
            rm -f /var/stafftestdir/distfiles/docker-compose.yml;
            cp -r /var/stafftestdir/distfiles/* ${{ env.PUBLISH_FILE_PATH }}; 
            cd ${{ env.DOCKER_FILE_PATH }};
            # docker-compose -f ${{ env.DOCKER_COMPOSE_FILENAME }} down && docker-compose -f ${{ env.DOCKER_COMPOSE_FILENAME }} up -d;
            rm -rf /var/stafftestdir/distfiles;

