name: Manual_Deploy
on:
  workflow_dispatch:

env:
    DOTNETVERSION: 8.0.x
    PATH_SLN: DataMigrationUtilit.CLI
    PATH_PROJECT_FOLDER: DataMigrationUtilit.CLI
    PROJECT_NAME: DataMigrationUtilit

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:  '${{env.DOTNETVERSION}}'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release

      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish
        # run: dotnet publish ${{ env.PATH_SLN }} --configuration Release --output ./publish --self-contained true --runtime win-x64

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./publish

      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: distfiles

      - name: Copy docker-compose.yml to distfiles
        run: |
          cp docker-compose.yml distfiles/;
          cp Dockerfile distfiles/

      - name: copy file to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DPLY_USER }}
          key: ${{ secrets.KEY }}
          overwrite: true
          source: distfiles/*
          target: /var/stafftestdir/

      - name: Update Server-Side Scripts
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DPLY_USER }}
          key: ${{ secrets.KEY }}
          script: |
            cp /var/stafftestdir/distfiles/Dockerfile /var/finaldockertestdir/; 
            cp /var/stafftestdir/distfiles/docker-compose.yml /var/finaldockertestdir/; 
            rm -f /var/stafftestdir/distfiles/Dockerfile;
            rm -f /var/stafftestdir/distfiles/docker-compose.yml;
            cp -r /var/stafftestdir/distfiles/* /var/finaltestdir/; 
            # docker-compose up -d; 
            rm -rf /var/stafftestdir/distfiles

      # - uses: geekyeggo/delete-artifact@v2
      #   name: Delete artefact
      #   with:
      #       name: my-artifact

